name: Deploy To-Do-List App

on:
  push:
    branches:
      - main  # Set this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install  # Use 'yarn install' if you're using Yarn

      - name: Build App
        run: npm run build  # Use the appropriate command to build your app into static files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /
