name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Set this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set this to your desired Node.js version

      - name: Install Dependencies
        run: npm install  # Use 'yarn install' if you're using Yarn

      - name: Build App (Optional)
        run: npm run build  # If your app requires a build step

      - name: Start Node.js Server
        run: npm start  # Use the appropriate command to start your server

